global:
    scrape_interval: 15s
    evaluation_interval: 15s
rule_files:
    - rule/record/*.yml
scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets:
            - localhost:9090
    - job_name: cadvisor
      static_configs:
        - targets:
            - 127.0.0.1:8080
            - 10.180.241.142:8080
