global:
    scrape_interval: 5s
    evaluation_interval: 5s
rule_files:
    - rule/record/*.yml
scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets:
            - localhost:9090
    - job_name: cadvisor
      static_configs:
        - targets:
            - localhost:8080
        - targets:
            - 10.180.241.142:8080
        - targets:
            - 192.168.1.0:8080
        - targets:
            - 192.168.2.0:8080
